import type {
  AuditEvent,
  ControlEvidence,
  MitigationTask,
  ReviewDecision,
  ThreatModelState,
  VersionSnapshot,
} from './domain'

const evidence: ControlEvidence[] = [
  {
    id: 'ev-01',
    controlId: 'ctl-01',
    title: '网关鉴权策略自动化测试',
    kind: 'test',
    reference: 'SEC-TEST-2048',
    collectedAt: '2026-08-18',
    expiresAt: '2026-11-18',
    owner: '安全测试组',
    valid: true,
  },
  {
    id: 'ev-02',
    controlId: 'ctl-02',
    title: '数据库透明加密配置快照',
    kind: 'config',
    reference: 'OPS-CFG-7721',
    collectedAt: '2026-05-10',
    expiresAt: '2026-08-10',
    owner: '平台运维组',
    valid: false,
  },
  {
    id: 'ev-03',
    controlId: 'ctl-03',
    title: '越权访问扫描报告',
    kind: 'scan',
    reference: 'APPSCAN-8891',
    collectedAt: '2026-09-04',
    expiresAt: '2026-12-04',
    owner: '应用安全组',
    valid: true,
  },
  {
    id: 'ev-04',
    controlId: 'ctl-04',
    title: '导出操作双人复核记录',
    kind: 'attestation',
    reference: 'ATT-2026-91',
    collectedAt: '2026-09-12',
    expiresAt: '2027-03-12',
    owner: '数据治理组',
    valid: true,
  },
]

const mitigations: MitigationTask[] = [
  {
    id: 'mit-01',
    threatId: 'thr-01',
    title: '收敛管理网关公网暴露面',
    owner: '林策',
    dueAt: '2026-10-20',
    status: 'in_progress',
    action: 'restrict',
    detail: '仅保留白名单办公网与管理专线访问。',
    evidenceIds: [],
    conflictGroup: 'gateway-access',
  },
  {
    id: 'mit-02',
    threatId: 'thr-01',
    title: '保留临时公网访问以便海外业务排障',
    owner: '周航',
    dueAt: '2026-10-25',
    status: 'todo',
    action: 'allow_with_condition',
    detail: '申请受控网络临时放行，需每日复核会话。',
    evidenceIds: [],
    conflictGroup: 'gateway-access',
  },
  {
    id: 'mit-03',
    threatId: 'thr-02',
    title: '轮换对象存储访问密钥',
    owner: '陈羽',
    dueAt: '2026-10-08',
    status: 'verifying',
    action: 'encrypt',
    detail: '完成密钥托管迁移并关闭长期静态凭证。',
    evidenceIds: ['ev-02'],
  },
  {
    id: 'mit-04',
    threatId: 'thr-03',
    title: '接入敏感导出行为监测',
    owner: '徐宁',
    dueAt: '2026-11-01',
    status: 'todo',
    action: 'monitor',
    detail: '对批量导出、异常来源地和超量下载建立告警。',
    evidenceIds: ['ev-04'],
  },
]

const decisions: ReviewDecision[] = [
  {
    id: 'dec-01',
    threatId: 'thr-01',
    actor: '王岚',
    role: 'security',
    decision: 'evidence_required',
    comment: '补充专线访问失败时的旁路告警证据。',
    createdAt: '2026-09-24T09:18:00+08:00',
    revision: 2,
  },
  {
    id: 'dec-02',
    threatId: 'thr-02',
    actor: '赵恺',
    role: 'development',
    decision: 'approved',
    comment: '密钥轮换已进入校验阶段。',
    createdAt: '2026-09-26T14:32:00+08:00',
    revision: 2,
  },
  {
    id: 'dec-03',
    threatId: 'thr-03',
    actor: '宋雨',
    role: 'business',
    decision: 'degrade',
    comment: '首期接受按日抽检，月结窗口需双人审批。',
    createdAt: '2026-09-27T11:05:00+08:00',
    revision: 2,
  },
]

const baselineVersions: VersionSnapshot[] = [
  {
    id: 'ver-01',
    revision: 1,
    label: 'v1.0 初始基线',
    createdAt: '2026-08-28T10:00:00+08:00',
    author: '王岚',
    notes: '完成系统边界、信任区与核心威胁基线。',
    threatIds: ['thr-01', 'thr-02', 'thr-03'],
    componentIds: ['cmp-01', 'cmp-02', 'cmp-03', 'cmp-04', 'cmp-05'],
    flowIds: ['flow-01', 'flow-02', 'flow-03', 'flow-04'],
    controlIds: ['ctl-01', 'ctl-02', 'ctl-03', 'ctl-04'],
    riskIds: ['risk-01', 'risk-02', 'risk-03'],
    affectedThreatIds: ['thr-01', 'thr-02', 'thr-03'],
  },
  {
    id: 'ver-02',
    revision: 2,
    label: 'v1.1 合作伙伴接入',
    createdAt: '2026-09-20T16:40:00+08:00',
    author: '林策',
    notes: '新增伙伴数据同步链路，重新评估跨信任区传输风险。',
    threatIds: ['thr-01', 'thr-02', 'thr-03'],
    componentIds: ['cmp-01', 'cmp-02', 'cmp-03', 'cmp-04', 'cmp-05', 'cmp-06'],
    flowIds: ['flow-01', 'flow-02', 'flow-03', 'flow-04', 'flow-05'],
    controlIds: ['ctl-01', 'ctl-02', 'ctl-03', 'ctl-04'],
    riskIds: ['risk-01', 'risk-02', 'risk-03', 'risk-04'],
    affectedThreatIds: ['thr-01', 'thr-02'],
  },
]

const audit: AuditEvent[] = [
  {
    id: 'aud-01',
    entityType: 'version',
    entityId: 'ver-02',
    action: '创建版本',
    actor: '林策',
    createdAt: '2026-09-20T16:40:00+08:00',
    detail: '创建 v1.1，受影响威胁 2 条。',
  },
  {
    id: 'aud-02',
    entityType: 'threat',
    entityId: 'thr-01',
    action: '要求补证',
    actor: '王岚',
    createdAt: '2026-09-24T09:18:00+08:00',
    detail: '安全负责人要求补充旁路告警证据。',
  },
  {
    id: 'aud-03',
    entityType: 'risk',
    entityId: 'risk-03',
    action: '风险接受即将过期',
    actor: '系统',
    createdAt: '2026-09-28T08:00:00+08:00',
    detail: '风险接受将在 2026-10-01 过期。',
  },
]

export const createSeedState = (): ThreatModelState => ({
  boundary: {
    id: 'boundary-01',
    name: '客户运营与分析平台',
    description: '用于客户经营分析、营销编排与数据产品发布。',
    owner: '数字业务平台部',
    inScope: 'Web 门户、运营 API、批处理、客户数据存储与第三方营销服务。',
    outOfScope: '线下门店终端、财务 ERP 与集团统一身份源。',
  },
  zones: [
    { id: 'zone-01', name: '公网接入区', level: 'internet', description: '面向客户与合作伙伴的公网入口。' },
    { id: 'zone-02', name: '业务隔离区', level: 'dmz', description: '网关、边缘服务及短期令牌处理区。' },
    { id: 'zone-03', name: '核心业务区', level: 'internal', description: '运营服务、规则引擎和工作流。' },
    { id: 'zone-04', name: '受限数据区', level: 'restricted', description: '客户敏感数据与审计记录。' },
  ],
  components: [
    {
      id: 'cmp-01',
      name: '运营管理门户',
      type: 'client',
      zoneId: 'zone-01',
      criticality: 'high',
      owner: '产品研发一组',
      description: '内部运营与合作伙伴用户访问入口。',
    },
    {
      id: 'cmp-02',
      name: 'API 安全网关',
      type: 'gateway',
      zoneId: 'zone-02',
      criticality: 'critical',
      owner: '基础架构组',
      description: '统一鉴权、限流与请求审计。',
    },
    {
      id: 'cmp-03',
      name: '客户运营服务',
      type: 'service',
      zoneId: 'zone-03',
      criticality: 'critical',
      owner: '增长工程组',
      description: '处理客户分群、触达策略和任务编排。',
    },
    {
      id: 'cmp-04',
      name: '客户主数据仓',
      type: 'data_store',
      zoneId: 'zone-04',
      criticality: 'critical',
      owner: '数据平台组',
      description: '存储客户身份、标签和互动记录。',
    },
    {
      id: 'cmp-05',
      name: '报表导出服务',
      type: 'service',
      zoneId: 'zone-03',
      criticality: 'high',
      owner: '数据产品组',
      description: '生成与分发经营分析报表。',
    },
    {
      id: 'cmp-06',
      name: '伙伴数据同步器',
      type: 'service',
      zoneId: 'zone-02',
      criticality: 'high',
      owner: '生态集成组',
      description: '与合作机构交换活动结果与归因数据。',
    },
  ],
  dependencies: [
    {
      id: 'dep-01',
      name: '短信触达云',
      vendor: '云信科技',
      purpose: '发送营销与验证码短信',
      dataClass: 'confidential',
      owner: '增长工程组',
      status: 'active',
    },
    {
      id: 'dep-02',
      name: '对象归档服务',
      vendor: '北辰云',
      purpose: '保存报表与审计归档',
      dataClass: 'restricted',
      owner: '数据平台组',
      status: 'review_due',
    },
    {
      id: 'dep-03',
      name: '伙伴归因接口',
      vendor: '东辰渠道',
      purpose: '接收渠道活动归因结果',
      dataClass: 'confidential',
      owner: '生态集成组',
      status: 'active',
    },
  ],
  flows: [
    {
      id: 'flow-01',
      name: '运营人员访问管理门户',
      sourceId: 'cmp-01',
      targetId: 'cmp-02',
      protocol: 'HTTPS',
      dataClass: 'internal',
      crossesTrustBoundary: true,
      description: '携带短期访问令牌进入业务隔离区。',
    },
    {
      id: 'flow-02',
      name: '网关调用运营服务',
      sourceId: 'cmp-02',
      targetId: 'cmp-03',
      protocol: 'mTLS',
      dataClass: 'confidential',
      crossesTrustBoundary: true,
      description: '转发已校验的业务请求与服务身份。',
    },
    {
      id: 'flow-03',
      name: '服务读写客户主数据',
      sourceId: 'cmp-03',
      targetId: 'cmp-04',
      protocol: 'TLS/PostgreSQL',
      dataClass: 'restricted',
      crossesTrustBoundary: true,
      description: '读取客户标签并写入活动执行结果。',
    },
    {
      id: 'flow-04',
      name: '报表导出到归档服务',
      sourceId: 'cmp-05',
      targetId: 'cmp-02',
      protocol: 'HTTPS',
      dataClass: 'restricted',
      crossesTrustBoundary: true,
      description: '经网关生成受限下载链接。',
    },
    {
      id: 'flow-05',
      name: '伙伴归因数据同步',
      sourceId: 'cmp-06',
      targetId: 'cmp-03',
      protocol: 'HTTPS/签名',
      dataClass: 'confidential',
      crossesTrustBoundary: true,
      description: '同步伙伴活动归因，使用独立签名密钥。',
    },
  ],
  controls: [
    {
      id: 'ctl-01',
      name: '统一身份与细粒度授权',
      type: 'preventive',
      status: 'effective',
      owner: '基础架构组',
      componentId: 'cmp-02',
      description: '基于角色与数据域的访问控制。',
      evidenceIds: ['ev-01'],
    },
    {
      id: 'ctl-02',
      name: '客户主数据静态加密',
      type: 'preventive',
      status: 'degraded',
      owner: '数据平台组',
      componentId: 'cmp-04',
      description: '数据库与备份介质透明加密。',
      evidenceIds: ['ev-02'],
    },
    {
      id: 'ctl-03',
      name: '导出越权检测',
      type: 'detective',
      status: 'effective',
      owner: '应用安全组',
      componentId: 'cmp-05',
      description: '对导出范围、频率与目标文件进行规则检测。',
      evidenceIds: ['ev-03'],
    },
    {
      id: 'ctl-04',
      name: '归档双人复核',
      type: 'corrective',
      status: 'planned',
      owner: '数据治理组',
      componentId: 'cmp-04',
      description: '高敏归档任务需申请人与复核人共同确认。',
      evidenceIds: ['ev-04'],
    },
  ],
  evidence,
  threats: [
    {
      id: 'thr-01',
      code: 'TM-001',
      title: '管理网关暴露导致凭证滥用',
      category: 'spoofing',
      description: '公网管理入口被枚举后，攻击者可能利用弱会话或泄露令牌进入运营服务。',
      severity: 'critical',
      status: 'mitigating',
      componentIds: ['cmp-01', 'cmp-02'],
      flowIds: ['flow-01'],
      externalDependencyIds: [],
      attackPathIds: ['path-01'],
      controlIds: ['ctl-01'],
      riskIds: ['risk-01'],
      reviewStatus: 'in_review',
      revision: 2,
    },
    {
      id: 'thr-02',
      code: 'TM-002',
      title: '对象存储长期密钥泄露',
      category: 'information_disclosure',
      description: '归档服务使用长期静态密钥，一旦泄露可批量访问受限报表。',
      severity: 'high',
      status: 'mitigating',
      componentIds: ['cmp-04', 'cmp-05'],
      flowIds: ['flow-04'],
      externalDependencyIds: ['dep-02'],
      attackPathIds: ['path-02'],
      controlIds: ['ctl-02', 'ctl-03'],
      riskIds: ['risk-02'],
      reviewStatus: 'approved',
      revision: 2,
    },
    {
      id: 'thr-03',
      code: 'TM-003',
      title: '敏感数据批量导出',
      category: 'information_disclosure',
      description: '具有报表权限的运营人员可能通过组合筛选获取超出职责范围的数据。',
      severity: 'high',
      status: 'open',
      componentIds: ['cmp-03', 'cmp-04', 'cmp-05'],
      flowIds: ['flow-03', 'flow-04'],
      externalDependencyIds: ['dep-02'],
      attackPathIds: ['path-03'],
      controlIds: ['ctl-03', 'ctl-04'],
      riskIds: ['risk-03'],
      reviewStatus: 'in_review',
      revision: 2,
    },
  ],
  attackPaths: [
    {
      id: 'path-01',
      name: '公网入口到运营服务',
      entryPoint: '管理门户公网域名',
      target: '客户运营服务',
      steps: ['探测管理入口', '获取有效会话', '绕过来源限制', '调用高权限运营接口'],
      likelihood: 4,
    },
    {
      id: 'path-02',
      name: '静态密钥到归档桶',
      entryPoint: '构建流水线环境变量',
      target: '对象归档服务',
      steps: ['读取长期密钥', '枚举归档桶', '下载历史报表'],
      likelihood: 3,
    },
    {
      id: 'path-03',
      name: '权限组合到批量导出',
      entryPoint: '运营管理门户',
      target: '客户主数据仓',
      steps: ['获取宽泛报表权限', '组合筛选缩小并扩大数据范围', '分批导出隐藏敏感字段'],
      likelihood: 4,
    },
  ],
  risks: [
    {
      id: 'risk-01',
      code: 'R-001',
      title: '管理入口凭证滥用',
      likelihood: 4,
      impact: 5,
      status: 'mitigating',
      owner: '基础架构组',
    },
    {
      id: 'risk-02',
      code: 'R-002',
      title: '归档凭证泄露',
      likelihood: 3,
      impact: 4,
      status: 'mitigating',
      owner: '数据平台组',
    },
    {
      id: 'risk-03',
      code: 'R-003',
      title: '敏感数据超范围导出',
      likelihood: 4,
      impact: 4,
      status: 'accepted',
      owner: '数据治理组',
      acceptanceExpiresAt: '2026-10-01',
      acceptanceCondition: '过渡期内按日抽检导出记录，发现异常立即冻结账号。',
    },
    {
      id: 'risk-04',
      code: 'R-004',
      title: '伙伴归因数据污染',
      likelihood: 3,
      impact: 3,
      status: 'open',
      owner: '生态集成组',
    },
  ],
  mitigations,
  decisions,
  versions: baselineVersions,
  audit,
  currentRevision: 2,
})
